name: thesis
channels:
  - conda-forge
dependencies:
  - python=3.11.1
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scipy
  - scikit-learn
  - jupyter
  - tensorflow
  - keras
  - papermill
  - pyarrow
  - klib
